name: update-sources

on:
  schedule:
    - cron: 0 */12 * * *
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    name: Update sources

    permissions:
      contents: write

    strategy:
      matrix:
        channel: [stable, beta, dev]

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: |
          nix shell --command bash -c '
            dart pub get
            dart run lib/main.dart ${{ matrix.channel }}
          '
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: updated sources for ${{ matrix.channel }} channel. [AUTO]"
